# Jekyll configuration


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Include the content directory for processing
include:
  - content

# Other default settings (customize as needed)
markdown: kramdown
permalink: pretty