# Jekyll configuration

# Site settings
title: "Barati - Data Platform and AI Engineer"
description: "Personal portfolio and resume site"
baseurl: ""
url: "https://barati.dev"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/

# Include the content directory for processing
include:
  - content
  - assets
  - _projects

# Other default settings
markdown: kramdown
permalink: pretty