# Jekyll configuration

# Site settings
title: "Barati - Data Platform and AI Engineer"
description: "Personal portfolio and resume site"
baseurl: ""
url: "https://barati.dev"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:title/  # ✓ Correct

# Include the content directory for processing
include:
  - content
  - assets
  - _projects  # ✓ Correct

# Exclude files and directories
exclude:
  - data-platform-ai--engineer.html
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md
  - package.json
  - package-lock.json
  - .git

# Other default settings
markdown: kramdown
permalink: pretty