# Jekyll configuration

# Site settings
baseurl: ""
url: ""

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Include the content directory for processing
include:
  - content
  - assets

# Other default settings
markdown: kramdown
permalink: pretty